# Site settings
title: Angel Gonzalez Mendoza
# twitter_username: namegoeshere
name: Angel GM

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/angel-gm
 - title: LinkedIn
   url: https://www.linkedin.com/in/angelgm531/
 - title: Email
   url: mailto:angel.gon531@gmail.com

#Skills appear as tags
skills:
 - R
 - Python
 - SQL
 - Excel/VBA
 - Access
 - Statistics
 - Machine Learning


#Work experience and education
roles:
 - title: Master of Science
   start: 2019
   end: 2021
   employer: Statistics
   description: Following the Data Science track. Expected graduation from Baruch College Spring 2021.
 - title: Financial Analyst
   start: 2016
   end: 2018
   employer: HSBC Bank
   description: |
     <ul> <li>Analyze the effects of interest rate changes and trade activity on the NPV of net interest income for a $40 billion investment
     portfolio consisting primarily of mortgage-backed securities.</li> <br>
     <li>Compile daily risk profile of a $500 million loan portfolio to traders and market risk management teams for hedging and compliance
     purposes; such risk metrics include duration and convexity.</li> <br>
     <li>Report daily profit/loss and mark-to-market of rate-locked loans and ensure accurate loan and market information within our MBS
     valuation framework. </li> <br> </ul>

 - title: Bachelor of Arts
   start: 2011
   end: 2016
   employer: Actuarial Science
   description: Graduated from Baruch College, with minors in <strong>Psychology</strong> and <strong>Technology, Business and the Internet</strong>
 - title: Admin&sdot; Assistant
   start: 2014
   end: 2015
   employer: G9C Fashion
   description: |
    <ul><li>Redesigned the process of producing and synthesizing logistics reports and reduced process time from 30 minutes to 5 minutes.</li><br>
    <li>Compiled all inventory reports to ensure accuracy and compliance with the warehouse’s policies.</li><br>
    <li>Automated reports in Excel to forecast future production supplies.</li><br></ul>

 - title: Admin&sdot; Assistant
   start: 2012
   end: 2015
   employer: Mago Landscaping
   description: Processed invoices for over 800 customers using QuickBooks. Dealt with company liabilities and customer service.



#Education area- merged with work experience instead
# education:
#  - level:
#    date: 2021
#    subject: Statistics - Data Science Track
#    school: CUNY Baruch College
#  - level: Bachelor of Arts (B.A.)
#    date: 2016
#    subject: Actuarial Science
#    school: CUNY Baruch College


# List of Github repo/projects to include
github:
 - angel-gm/angel-gm.github.io
 - angel-gm/angel-gm.github.io
 - angel-gm/angel-gm.github.io



intro: |
  I am a student pursuing a master’s degree in Statistics, with a concentration in Data Science, at Baruch College in NYC. I’ve previously worked at HSBC Bank as a financial analyst after graduation from Baruch with a major in Actuarial Science and passing 3 actuarial exams.
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <a target="_blank" href="https://www.soa.org/education/exam-req/edu-exam-p-detail/" >Passed SOA Exam P</a><br/>
   <a target="_blank" href="https://www.soa.org/education/exam-req/edu-exam-fm-detail/" >Passed SOA Exam FM</a><br/>
   <a target="_blank" href="https://www.soa.org/education/exam-req/edu-exam-ifm-detail/" >Passed SOA Exam IMF</a><br/>
   <a target="_blank" href="https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/" >Completed 'Python for Data Science and Machine Learning Bootcamp'</a>.<br/>
   <a target="_blank" href="https://www.datacamp.com/courses/communicating-with-data-in-the-tidyverse" >Completed 'Communicating with Data in the Tidyverse'</a>
